### PR TITLE
Fix test eq type for inner type

### PR DESCRIPTION
**Pull request by kessido**
test_eq_type did not work for inner types. simple example:
`test_eq_type([[1]],[[1.0]])` does not fail.

I implemented a recursive comparison instead.

### CODE REVIEW

**Comment by jph00** [comment]
That's a good idea, but I think it's trying to do too much. As a result, performance is bad for tensors/arrays/etc, since listifying them is really slow. Also, this implementation is a bit more complicated than I'm comfortable with.

Arrays etc should already be testing the inner type, shouldn't they? So maybe that stuff isn't needed?

**Review by jph00 — CHANGES_REQUESTED** [review]
Simplify and improve performance.

**Comment by kessido** [comment]
> Simplify and improve performance.

Working on it now.

**Comment by kessido** [comment]
Simplified&Improved performance. @jph00 please review :)

> That's a good idea, but I think it's trying to do too much. As a result, performance is bad for tensors/arrays/etc, since listifying them is really slow. Also, this implementation is a bit more complicated than I'm comfortable with.
> 
> Arrays etc should already be testing the inner type, shouldn't they? So maybe that stuff isn't needed?

Arrays doesn't test inner types, so it's still needed.
Also for cases where np.array uses object, only testing dtype can be misleading.

**Comment by hamelsmu** [comment]
@kessido can you resolve conflicts?

**Comment by jph00** [comment]
Closing this since it's gotten stale, and I'm still not sure this is actually behavior we want.

**Pull request closed without merging**
