### PR TITLE
Nested attr supporting keys

### PR DESCRIPTION
**Pull request by Isaac-Flath**
Added support for keys in `nested_attr`

@jph00

### CODE REVIEW

**Comment by jph00** [comment]
Can you look at the failing CI @Isaac-Flath ? Lemme know if you need help fixing it.

**Comment by jph00** [comment]
That was fast :)

**Comment by jph00** [comment]
Got another CI issue @Isaac-Flath !

**Comment by Isaac-Flath** [comment]
Argh, another issue.  I am going to sleep on this and fix it in the morning.  I will get the fastai testing figured out for local tests so I can test it before the next attempt.

**Comment by Isaac-Flath** [comment]
@jph00 All tests pass now, but it feels like there should be a better way.   I tried looking for a `__getattr__` method and tried checking for types, but wasn't able to get something that worked reliably in all cases without doing the `try` and catching the exception if it happens.

**Comment by jph00** [comment]
@Isaac-Flath i think you want the hasattr() function

**Comment by Isaac-Flath** [comment]
I used it in some of the previous versions that were failing the integration tests, and tried several things using it and kept failing test.  But just added it back and it seems to work on local fastcore and fastai tests, so I must have been doing something different wrong.

Anyway - much better.  Thank you!

**Comment by jph00** [comment]
Thanks @Isaac-Flath . In your other PR that uses this, please update settings.ini to require this version of fastcore , and at-mention when that's ready, and I'll release both.

**Pull request merged**
