### PR TITLE
support windows: only add lock if it runs parallelly

### PR DESCRIPTION
**Pull request by mszhanyi**
1. support windows: 00_test and 03_xtras are not compatible with Windows
2. Fix https://github.com/fastai/nbdev/issues/393
If the functions runs sequentially, it doesn't need a lock. 
And multiprocess.manager().lock() spawns one new process, notebook will be stuck on Windows.

### CODE REVIEW

**Comment by mszhanyi** [comment]
@jph00 could you please take a look?

**Comment by jph00** [comment]
Great! :)

**Comment by jph00** [comment]
It's currently marked as a draft. Please mark it as ready to review if you want it merged.

**Comment by mszhanyi** [comment]
> It's currently marked as a draft. Please mark it as ready to review if you want it merged.



> It's currently marked as a draft. Please mark it as ready to review if you want it merged.

@jph00 ， I marked it as draft because I need more time to enable all fastcore support windows.
Now. all tests are passed in windows.
image

**Comment by mszhanyi** [comment]
FYI.
1. nbdev_clean_nbs always update \r to \n in notebooks. 
   so I have to remove as_bytes=True in test_eq(run('cmd /c echo hi'), 'hi') on Windows
2. def run(cmd, *rest, ignore_ex=False, as_bytes=False, stderr=False) doesn't support redirection in command, does it matter?

**Comment by jph00** [comment]
> 2\. def run(cmd, *rest, ignore_ex=False, as_bytes=False, stderr=False) doesn't support redirection in command, does it matter

No I don't think so - you can use `subprocess.run(..., shell=True)` if you need redirection, or use a more full featured python lib like [sh](https://amoffat.github.io/sh/)

**Comment by jph00** [comment]
> > It's currently marked as a draft. Please mark it as ready to review if you want it merged.
> 
> > It's currently marked as a draft. Please mark it as ready to review if you want it merged.
> 
> @jph00 ， I marked it as draft because I need more time to enable all fastcore support windows.
> Now. all tests are passed in windows.
> image

Excellent - thank you!

**Pull request merged**
