### PR TITLE
extend test_eq_type

### PR DESCRIPTION
**Pull request by ddobrinskiy**
Change the behaviour of `test_eq_type` to fail if comparing tensors with different dtypes

previously this would pass: `test_eq_type(torch.zeros(10), torch.zeros(10, dtype=torch.float64))`

Now it does not

### CODE REVIEW

**Comment by jph00** [comment]
Good idea!

**Comment by jph00** [comment]
Oh actually we can't do this because it introduces dependencies on pytorch, numpy, and pandas.

**Comment by ddobrinskiy** [comment]
Oh right, this makes sense.

I did not notice that those packages are part of **dev** dependencies, not main ones.

**Pull request merged**
