### PR TITLE
Clean up docs for utils

### PR DESCRIPTION
**Pull request by hamelsmu**

### CODE REVIEW

**Comment by hamelsmu** [comment]
@jph00 this is ready for review

**Comment by hamelsmu** [comment]
@jph00 I made the following changes:

- removed `show_doc` from all functions, which got rid of the vast majority of `show_docs`
- I kept `show_doc` on most classes to indent them to level 4 to be peers of functions within the same group
- I kept `show_doc` in special cases where I needed to hide something, or where I needed show_doc specifically to accomplish something.  

LMK if that works

**Comment by hamelsmu** [comment]
Actually give me a moment, I'll tag you again I just realized I can get rid of more `show_doc`

**Comment by hamelsmu** [comment]
@jph00 ok this is now ready for review.

**Comment by jph00** [comment]
Great!

**Pull request merged**
