### PR TITLE
Fix writing string as bytes in urlsave

### PR DESCRIPTION
**Pull request by jochym**
The `urlsave` function attempts to write bytes which are loaded and decoded to string in `urlread`. This switches off the decoding to have bytes object to write. This issue shows up in the `nbdev_new` command.

### CODE REVIEW

**Comment by jochym** [comment]
I really have no idea how to clean up this conflict properly. Would you care to help @jph00 ?

**Comment by jph00** [comment]
Please grab the latest nbdev and rebuild libs, and it should be sorted.

**Comment by jochym** [comment]
Do you mean you fixed this in nbdev? Because I think the code in fastcore may be actually wrong - it reads bytes, decodes and attempts to write it as bytes - this seems wrong.
But if you mean fixing the conflict - I will try

**Comment by jph00** [comment]
Sorry I meant the *conflict* should be resolved with the latest nbdev.

**Comment by jochym** [comment]
Thanks @jph00 , but I am still getting issues with building fastcore. After running `nbdev_build_libs` and `nbdev_clean_nbs` I cannot run `nbdev_build_docs`. All these:
```
index.ipynb
03_xtras.ipynb
03b_net.ipynb
07_meta.ipynb
03a_parallel.ipynb
05_transform.ipynb
08_script.ipynb
04_dispatch.ipynb
01_basics.ipynb
00_test.ipynb
02_foundation.ipynb
```
cannot be converted with similar message:
```

An error occurred while executing the following cell:
------------------
from nbdev.showdoc import show_doc
from fastcore.foundation import *
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-1-f76626eaec24> in <module>
----> 1 from nbdev.showdoc import show_doc
      2 from fastcore.foundation import *

~/miniconda3/envs/nbd/lib/python3.9/site-packages/nbdev/__init__.py in <module>
      2
      3 from fastcore.imports import IN_IPYTHON
----> 4 from .imports import *
      5
      6 if IN_IPYTHON:

~/miniconda3/envs/nbd/lib/python3.9/site-packages/nbdev/imports.py in <module>
      1 from fastcore.imports import *
----> 2 from fastcore.foundation import *
      3 from fastcore.utils import *
      4 from fastcore.test import *
      5

~/Projects/fastcore/fastcore/foundation.py in <module>
    223 # Cell
    224 #hide
--> 225 L.__signature__ = pickle.loads(b'\x80\x03cinspect\nSignature\nq\x00(cinspect\nParameter\nq\x01X\x05\x00\x00\x00itemsq\x02cinspect\n_ParameterKind\nq\x03K\x01\x85q\x04Rq\x05\x86q\x06Rq\x07}q\x08(X\x08\x00\x00\x00_defaultq\tNX\x0b\x00\x00\x00_annotationq\ncinspect\n_empty\nq\x0bubh\x01X\x04\x00\x00\x00restq\x0ch\x03K\x02\x85q\nRq\x0e\x86q\x0fRq\x10}q\x11(h\th\x0bh\nh\x0bubh\x01X\x08\x00\x00\x00use_listq\x12h\x03K\x03\x85q\x13Rq\x14\x86q\x15Rq\x16}q\x17(h\t\x89h\nh\x0bubh\x01X\x05\x00\x00\x00matchq\x18h\x14\x86q\x19Rq\x1a}q\x1b(h\tNh\nh\x0bubtq\x1c\x85q\x1dRq\x1e}q\x1fX\x12\x00\x00\x00_return_annotationq h\x0bsb.')
    226
    227 # Cell

~/miniconda3/envs/nbd/lib/python3.9/inspect.py in __setstate__(self, state)
   2561     def __setstate__(self, state):
   2562         self._default = state['_default']
-> 2563         self._annotation = state['_annotation']
   2564
   2565     @property

KeyError: '_annotation'
KeyError: '_annotation'
```
I can always make the whole thing anew - since it is jus one commit. But I am worried about something like this happening in one of my nbdev projects...

**Comment by jph00** [comment]
That looks to be not the current master version of fastcore.

**Comment by jochym** [comment]
OK. I will resync

**Pull request closed without merging**
