### PR TITLE
Update 03_xtras: typo becuase => because

### PR DESCRIPTION
**Pull request by Naereen**
Hello there,
I'm enjoying reading https://fastcore.fast.ai/ documentation, and I found this one-letter typo in https://fastcore.fast.ai/xtras.html#run
Thanks for your amazing work, kind regards from France. -- @Naereen

### CODE REVIEW

**Comment by insolor** [comment]
Also, there's a typo in "ignore" ("ingore") in that line

**Comment by Naereen** [comment]
Thanks @insolor, I didn't see this typo! I fixed it with another one-letter commit.

**Comment by Naereen** [comment]
Hi @insolor and others, could you merge? Thanks :sun_with_face: !

**Comment by insolor** [comment]
@Naereen, sorry, I have no power here. Just passed by 🙂

**Comment by Naereen** [comment]
Then I don't know whom to ping, @whoahbot @michaelaye @butchland maybe?

**Comment by michaelaye** [comment]
I’m like you, trying to give back by submitting small fixes. I have no power here either.

**Pull request merged**
